<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="7" time="0.176" timestamp="2022-08-19T14:33:06.753238" hostname="Win10-2022QKPFU"><testcase classname="test_dir.test_fixtures_01" name="test_multiply_3_4" time="0.003" /><testcase classname="test_dir.test_fixtures_01" name="test_multiply_a_3" time="0.001" /><testcase classname="test_dir.test_parameterize" name="test_pow[case1]" time="0.001" /><testcase classname="test_dir.test_parameterize" name="test_pow[case2]" time="0.001" /><testcase classname="test_dir.test_parameterize" name="test_pow[case3]" time="0.001" /><testcase classname="test_dir.test_parameterize" name="test_pow[case4]" time="0.001" /><testcase classname="test_dir.test_sample" name="test_answer" time="0.001"><failure message="assert 4 == 5&#10; +  where 4 = inc(3)">def test_answer():
&gt;       assert inc(3) == 5
E       assert 4 == 5
E        +  where 4 = inc(3)

test_dir\test_sample.py:7: AssertionError</failure></testcase></testsuite></testsuites>